In [207]:
from playwright.async_api import async_playwright
import asyncio
import os
import pandas as pd
from pathlib import Path
import openpyxl
import tabula

In [277]:
# Určení proměnných
# url = odkaz na stránky se stažením souborů
# download_path = cesta kam se mají uložit

url = "https://mpo.gov.cz/cz/podnikani/zivnostenske-podnikani/statisticke-udaje-o-podnikatelich/pocty-podnikatelu-dle-obcanstvi-podnikajicich-v-ceske-republice--151024/"
download_path = "./"

In [267]:
# Automatizace převodu celé složky .XLSX na správné .CSV
# Otevře, převede na .csv, odebere 4 první řádky, 
# resetuje index, uloží jako .csv

download_path = "./Download"
export_path = "./Download_CSV"


folder_path = Path(download_path)

'''
TEST - vypíše všechny soubory v Download složce

files = list(folder_path.iterdir())
for x in files:
    print(x)
'''

processed = 0
#filenames = []
# Prochází všechny soubory ve složce
for file in folder_path.iterdir():
    if file.is_file() and not file.name.startswith('.'):  # Kontrola, zda jde o soubor
        processed += 1
        #filenames.append(file.name)
        #print(f"Zpracovává se soubor: {file.name}")

        # Zkusmo otevřít jeden .xlsx soubor a uložit ho jako .csv
        file_path = (f"{download_path}/{file.name}")
        df = pd.read_excel(file_path, engine='openpyxl')

        newname = (file.name).replace(".xlsx", "") # odstranění .xlsx ze starého názvu
        csv_path = (f"{export_path}/{newname}.csv") # nový název pro uložení
        df.to_csv(csv_path, index=False)
        print(f"{processed} Soubor {csv_path} úspěšně převeden", end=" ")

        # Otevřeme v pandasu a zahodíme 4 zbytečné řádky + resetujeme index
        df = pd.read_csv(csv_path, header=None)  # Načte bez záhlaví
        dff = df.iloc[4:].reset_index(drop=True)  # Odstraní první 4 řádky a resetuje index
        dff.columns = dff.iloc[0]  # Nastaví 5. řádek (který je teď první po odstranění) jako názvy sloupců
        dff = dff.drop(0).reset_index(drop=True)  # Odstraní řádek použitý jako názvy sloupců

        # Uloží jako CSV
        dff.to_csv(csv_path, index=False)
        print(f"+ uložen", end="\n")

print(f"Ve složce je {processed} souborů.")
#print(f"Toto jsou jejich jména: {filenames}")

1 Soubor ./Download_CSV/2024_3.csv úspěšně převeden + uložen
2 Soubor ./Download_CSV/2019_1.csv úspěšně převeden + uložen
3 Soubor ./Download_CSV/2016_4.csv úspěšně převeden + uložen
4 Soubor ./Download_CSV/2017_1.csv úspěšně převeden + uložen
5 Soubor ./Download_CSV/2024_2.csv úspěšně převeden + uložen
6 Soubor ./Download_CSV/2018_4.csv úspěšně převeden + uložen
7 Soubor ./Download_CSV/2018_3.csv úspěšně převeden + uložen
8 Soubor ./Download_CSV/2018_2.csv úspěšně převeden + uložen
9 Soubor ./Download_CSV/2017_4.csv úspěšně převeden + uložen
10 Soubor ./Download_CSV/2018_1.csv úspěšně převeden + uložen
11 Soubor ./Download_CSV/2020_1.csv úspěšně převeden + uložen
12 Soubor ./Download_CSV/2017_2.csv úspěšně převeden + uložen
13 Soubor ./Download_CSV/2019_3.csv úspěšně převeden + uložen
14 Soubor ./Download_CSV/2024_1.csv úspěšně převeden + uložen
15 Soubor ./Download_CSV/2019_2.csv úspěšně převeden + uložen
16 Soubor ./Download_CSV/2017_3.csv úspěšně převeden + uložen
Ve složce je 16 souborů.

In [256]:
# Definice proměnných pro další zpracování tabulek

csv_file = "./Download_CSV/2016_2.csv"

suffix = csv_file.strip(".csv")
suffix = suffix[-1]

rok = csv_file.strip(".csv")
rok = rok[-6:-2]

In [257]:
# Otevřeme v pandasu jeden soubor a zkusíme řádky pojmenovat s příponou Q + číslo podle názvu souboru

df = pd.read_csv(csv_path)  # Read without headers
df["Rok"] = rok
df["Q"] = suffix
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,Rok,Q
0,Občanství,Kód,Kód zn.,Kód zn.,Hlavní město Praha,Středočeský kraj,Jihočeský kraj,Plzeňský kraj,Karlovarský kraj,Ústecký kraj,...,Královéhradecký kraj,Pardubický kraj,Kraj Vysočina,Jihomoravský kraj,Olomoucký kraj,Moravskoslezský kraj,Zlínský kraj,Součet,2016,2
1,Afghánistán,004,AF,AFG,16,7,0,0,2,7,...,0,0,1,12,3,2,0,52,2016,2
2,Albánie,008,AL,ALB,14,7,4,1,1,3,...,2,1,1,2,1,1,4,43,2016,2
3,Alžírsko,012,DZ,DZA,92,19,4,0,1,7,...,1,1,1,8,3,2,1,142,2016,2
4,Angola,024,AO,AGO,10,2,2,0,0,2,...,1,1,0,6,3,1,2,33,2016,2

In [275]:
# Automat - přidá dva sloupce "rok" a "Q" jako kvartál

folder_path = Path("./Download_CSV")

for file in folder_path.iterdir():
    if file.is_file() and not file.name.startswith('.'):
        csv_file = file.name
        csv_path = (f"{folder_path}/{csv_file}")

        # Definice proměnných q, rok
        q = csv_file.strip(".csv")
        q = suffix[-1]

        rok = csv_file.strip(".csv")
        rok = rok[-6:-2]

        df = pd.read_csv(csv_path)
        df["Rok"] = rok
        df["Q"] = q

        df.to_csv(csv_path, index=False)

        print(f"Soubor {csv_file} byl změněn", end="\n")

Soubor 2016_2.csv byl změněn

In [276]:
df.head(5)

,Občanství,Kód,Kód zn.,Kód zn..1,Hlavní město Praha,Středočeský kraj,Jihočeský kraj,Plzeňský kraj,Karlovarský kraj,Ústecký kraj,...,Královéhradecký kraj,Pardubický kraj,Kraj Vysočina,Jihomoravský kraj,Olomoucký kraj,Moravskoslezský kraj,Zlínský kraj,Součet,Rok,Q
0,Afghánistán,4,AF,AFG,15,6,0,0,1,6,...,0,0,1,12,4,2,0,48,2016,2
1,Albánie,8,AL,ALB,10,8,4,1,1,2,...,2,1,0,2,2,1,3,38,2016,2
2,Alžírsko,12,DZ,DZA,99,21,3,0,1,9,...,1,1,0,8,2,3,0,150,2016,2
3,Angola,24,AO,AGO,9,2,2,0,0,3,...,1,1,0,6,3,4,2,35,2016,2
4,Ázerbájdžán,31,AZ,AZE,37,5,0,2,4,4,...,1,0,0,2,4,0,0,59,2016,2

In [294]:
df.shape
#df.columns

(162, 21)

In [295]:
df.columns

Index(['Občanství', 'Kód', 'Kód zn.', 'Kód zn..1', 'Hlavní město Praha',
       'Středočeský kraj', 'Jihočeský kraj', 'Plzeňský kraj',
       'Karlovarský kraj', 'Ústecký kraj', 'Liberecký kraj',
       'Královéhradecký kraj', 'Pardubický kraj', 'Kraj Vysočina',
       'Jihomoravský kraj', 'Olomoucký kraj', 'Moravskoslezský kraj',
       'Zlínský kraj', 'Součet', 'Rok', 'Q'],
      dtype='object')

In [307]:
for x in df["Občanství"].values:
    print(x)

Afghánistán
Albánie
Alžírsko
Angola
Ázerbájdžán
Argentina
Austrálie
Rakousko
Bangladéš
Arménie
Belgie
Bolívie
Bosna a Hercegovina
Brazílie
Britské Panenské ostrovy
Kosovo
Bulharsko
Myanmar
Bělorusko
Kambodža
Kamerun
Kanada
Šrí Lanka
Čad
Chile
Čína
Tchaj-wan
Vánoční ostrov
Kolumbie
Konžská republika
Demokratická republika
Kongo
Kostarika
Chorvatsko
Kuba
Kypr
Česko
Benin
Dánsko
Dominikánská republika
Ekvádor
Salvador
Etiopie
Eritrea
Estonsko
Finsko
Alandy
Francie
Francouzská Guyana
Gruzie
Gambie
Palestina
Německo
Ghana
Řecko
Guatemala
Guinea
Guyana
Honduras
Hongkong
Maďarsko
Island
Indie
Indonésie
Írán
Irák
Irsko
Izrael
Itálie
Pobřeží slonoviny
Jamajka
Japonsko
Kazachstán
Jordánsko
Keňa
Korejská lidově
demokratická republika
Korejská republika
Kuvajt
Kyrgyzstán
Laos
Libanon
Lotyšsko
Libérie
Libye
Litva
Lucembursko
Madagaskar
Malajsie
Mali
Malta
Mauritánie
Mauricius
Mexiko
Monako
Mongolsko
Moldavsko
Černá Hora
Maroko
Namibie
Nepál
Nizozemsko
Nizozemské Antily
Curacao
Vanuatu
Nový Zéland
Niger
Nigérie
Norsko
Pákistán
Panama
Paraguay
Peru
Filipíny
Polsko
Portugalsko
Guinea-Bissau
Portoriko
Katar
Rumunsko
Rusko
Rwanda
Svatý Kryštof a Nevis
Svatá Lucie
Svatý Tomáš a Princův
ostrov
Saúdská Arábie
Senegal
Srbsko
Singapur
Slovensko
Vietnam
Slovinsko
Somálsko
Jižní Afrika
Zimbabwe
Španělsko
Súdán
Západní Sahara
Surinam
Švédsko
Švýcarsko
Sýrie
Tádžikistán
Thajsko
Tunisko
Turecko
Turkmenistán
Uganda
Ukrajina
Makedonie
Egypt
Velká Británie
Guernsey
Tanzanie
Spojené státy
Burkina Faso
Uruguay
Uzbekistán
Venezuela
Jemen
Srbsko a Černá Hora
Zambie
Součet
Z toho cizinci

In [273]:
''''
JEDNORÁZOVÉ SPRAVENÍ SOUBORU 2016_2.csv

file_path = 'Down/2016_2.csv'  # Replace with your file path
df = pd.read_csv(file_path, sep=';')

# Save the file with commas as the delimiter
output_path = 'fixed_file.csv'  # Replace with your desired output path
df.to_csv(output_path, index=False, sep=',')
'''

In [ ]:
'''
------------------------------ THE END ---------------------------------
'''